language: python
python:
    - 2.7
node_js:
    - 0.10
before_install:
    - scripts/ci-setup.sh
script:
    - scripts/ci.sh
notifications:
  slack: ajenti:ANVVc21AEbnRLYAWBZlhzAtW 
sudo: false
addons:
  apt:
    packages:
    - python-lxml 
    - python-dbus 
    - python-lxml 
    - libaugeas-dev
    - augeas-tools
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/virtualenv
