auth:
  allow_sudo: true
  emails: {}
  provider: lm
  users: null
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8001
color: default
language: de
linuxmuster:
  initialized: false
  is-configured: false
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: OtxKkVbtTmGw0rBu
    host: server
    searchdn: DC=linuxmuster,DC=lan
  provision: false
max_sessions: 9
name: server.linuxmuster.lan
restricted_user: nobody
ssl:
  certificate: /etc/webui/webui.pem
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: true
